Documentation for second HX711 and Scale Config on the Website
rancilio-pid/ranciliopid-handbook pull request #71
Opened 2024-01-20 13:16 UTC by FabianSperrle

2024-01-20 16:23 UTC, janwillies commented on img/website_with_scale_calibration.png
Calibration mode seems a bit generic. Maybe `toggle scale calibration`?

2024-01-22 23:39 UTC, LoQue90 requested changes

2024-01-22 23:39 UTC, LoQue90 commented on de/hardware/Waage.md
> +Tragt hier das Gewicht eures Kalibiergewichts ein. Den/Die Kalibrierungsfaktor(en) könnt ihr ignorieren. Diese Werte werden während der Kalibrierung überschrieben.
Kalibriergewicht

2024-03-09 00:46 UTC, LoQue90 approved these changes

2024-03-09 00:46 UTC, merged