Doc: Added first draft of documentation (german) for the new watersensor
rancilio-pid/ranciliopid-handbook pull request #76
Opened 2024-02-04 20:59 UTC by schober-ch

First draft of documentation for the new watersensor feature. Please have a look and give feedback/comments.

Open questions from my side:
1. Should we add the sensor to the Materialliste?
2. Is the new file and jekyll(?) config correct? I'll try to find time to figure out the local build process (promised), but perhaps we can add some info to the README.md as well?

2024-02-11 00:13 UTC, LoQue90 requested changes

2024-02-11 00:13 UTC, LoQue90 commented on de/hardware/Wasserstandssensor.md
> +(== es erfolgt kein Heizvorgang mehr). Ein laufender Espresso-Bezug wird nicht unterbrochen.
Würde hier eher schreiben das einfach keine laufende Aktion welche die Pumpe benutzt abgebrochen wird. Nur eben nicht gestartet werden kann wenn der Wasserstand zu niedrig ist.

2024-02-11 00:13 UTC, LoQue90 commented on de/hardware/Wasserstandssensor.md
> +* Gelb: Signal (je nach PCB-Revision, z.B. V1.3 Pin 1023)
gerne hier auch die aktelle rev 1.5 und den passenden Header verweisen (Pin bleibt der gleiche)

2024-02-11 00:13 UTC, LoQue90 commented on img/watersensor_0.png
der Bilder Ordner ist Chaos, da würde ich gerne mehr ordnung reinbringen.
Würdest du die Bilder in img/hardware/watersensor/ packen?

2024-02-13 16:46 UTC, schober-ch commented on de/hardware/Wasserstandssensor.md
> +(== es erfolgt kein Heizvorgang mehr). Ein laufender Espresso-Bezug wird nicht unterbrochen.
Habs etwas umgeschrieben

2024-02-13 16:47 UTC, schober-ch commented on de/hardware/Wasserstandssensor.md
> +* Gelb: Signal (je nach PCB-Revision, z.B. V1.3 Pin 1023)
Habe auf den 1.5er verwiesen, der header (W_SENS) wird gleich unter dem nächsten Bild benannt - möchtest du das hier oben nochmal drinnen haben? Hätte es jetzt so gelassen

2024-02-13 16:47 UTC, schober-ch commented on img/watersensor_0.png
done

2024-02-14 20:59 UTC, LoQue90 commented
Danke fürs schreiben :)

2024-02-14 20:59 UTC, LoQue90 approved these changes

2024-02-14 20:59 UTC, merged