Wordings+formatting in german manual, and adding translations
rancilio-pid/ranciliopid-handbook pull request #91
Opened 2024-02-17 23:17 UTC by eliba

(this is a replica of #72, which I messed up with git. This PR should now include a simple merge commit of the changes that happened on `main` in the meantime).

Heyho,
this PR is wild (sorry) and does a handful of things at once:

    Made the warning message about working with high voltages multi-language in _config.yml
    Replaced some dead or wrong links
    bulk-renamed WiFiManager, userConfig.h, ESP32, ESP8266 and probably more
    Named the hardware PCB "base board" in english texts, to make it easier to distinguish from other parts
    Formated filenames, buttons etc with code
    Included empty lines around headings (two above, one below) and pictures/codeblocks (one above, one below)
    Shortened URLs to the necessary part
    Translated german pages up to software chapter
    Added a small section to the README on how to build the project locally

Someone should have a look at the specific wordings about electronics in the bottom of 'bom.md', I'm not an electrician.

Thanks for this cool project! ✌️

2024-02-22 22:34 UTC, LoQue90 requested changes

2024-02-22 22:34 UTC, LoQue90 commented on en/bom.md
> +**Update 07.12.23: Currently there are no PCBs available. Expected date for new orders is january.**
die zeile kann ganz raus

2024-02-22 22:34 UTC, LoQue90 commented on en/bom.md
> + * Adhesive dots
adhesive pcb holder

2024-02-22 22:34 UTC, LoQue90 commented on en/bom.md
> +
Teile davon hab ich ja ausgelagert zu den Infos der Platinen, magst du dir da nochmal den aktuellen Stand von im DE Handbuch anschauen und das hier anpassen?

2024-02-22 22:34 UTC, LoQue90 commented on en/intro/version3.md
> +You can find out the IP address of your ESP by checking the list of connected WiFi devices in your home router, or with the monitor command in PlatformIO, while the ESP is still connected via USB. We
blynk ist komplett raus, kann hier auch weg

2024-02-22 22:34 UTC, LoQue90 commented on en/intro/version3.md
> +Schritt | Erklärung
ist noch nicht übersetzt

2024-02-22 22:34 UTC, LoQue90 commented on de/intro/version3.md
>  Wir haben eine eigene auf dem ESP gehostet Webseite. Im Normalfall kann die Webseite über [http://`<<HOSTNAME>>`.local](#webseite) aufgerufen werden. Den hostname findet man in `platform.ino` unter d
upload_port

2024-02-22 22:34 UTC, LoQue90 commented on de/software-part-I/Userconfig.md
> +
Grafana gibt es nicht mehr, kann also auch weg

2024-02-22 22:34 UTC, LoQue90 commented on de/software-part-I/programmcode.md
> +Ab der Version 4 für den ESP32 beziehungsweise für den ESP8266 (bis Version 3.1.3)  werden folgende Softwaretools benötigt:
ESP8266 ab Version 3.x

2024-02-22 22:34 UTC, LoQue90 commented on en/intro/introduction.md
> +Heizung | Heating
Eigentlich braucht es diese IDs hier doch garnicht?

2024-02-23 10:58 UTC, eliba commented on en/intro/introduction.md
> +Heizung | Heating
Die referenzieren die IDs auf dem Bild unten drunter

2024-02-23 11:00 UTC, eliba commented on en/bom.md
> +
hab ich rausgemacht und die englische Übersetzung hinzugefügt

2024-02-23 20:52 UTC, LoQue90 approved these changes

2024-02-23 20:52 UTC, merged